# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

build:
	$(MAKE) -C enclave/build
	$(MAKE) -C host/build

clean:
	$(MAKE) -C enclave/build clean
	$(MAKE) -C host/build clean

run1:
	host/build/lnteehost ./enclave/build/lntee.signed 10000

run2:
	host/build/lnteehost ./enclave/build/lntee.signed 10001

run3:
	host/build/lnteehost ./enclave/build/lntee.signed 10002

run4:
	host/build/lnteehost ./enclave/build/lntee.signed 10003

run5:
	host/build/lnteehost ./enclave/build/lntee.signed 10004

run6:
	host/build/lnteehost ./enclave/build/lntee.signed 10005

run7:
	host/build/lnteehost ./enclave/build/lntee.signed 10006

run8:
	host/build/lnteehost ./enclave/build/lntee.signed 10007

run9:
	host/build/lnteehost ./enclave/build/lntee.signed 10008

run10:
	host/build/lnteehost ./enclave/build/lntee.signed 10009

run11:
	host/build/lnteehost ./enclave/build/lntee.signed 10010

run12:
	host/build/lnteehost ./enclave/build/lntee.signed 10010

run13:
	host/build/lnteehost ./enclave/build/lntee.signed 10011

run14:
	host/build/lnteehost ./enclave/build/lntee.signed 10012

run15:
	host/build/lnteehost ./enclave/build/lntee.signed 10013

run16:
	host/build/lnteehost ./enclave/build/lntee.signed 10014

run17:
	host/build/lnteehost ./enclave/build/lntee.signed 10015

run18:
	host/build/lnteehost ./enclave/build/lntee.signed 10016

run19:
	host/build/lnteehost ./enclave/build/lntee.signed 10017

run20:
	host/build/lnteehost ./enclave/build/lntee.signed 10018

run21:
	host/build/lnteehost ./enclave/build/lntee.signed 10019

run22:
	host/build/lnteehost ./enclave/build/lntee.signed 10020

run23:
	host/build/lnteehost ./enclave/build/lntee.signed 10021

run24:
	host/build/lnteehost ./enclave/build/lntee.signed 10022

run25:
	host/build/lnteehost ./enclave/build/lntee.signed 10023

run26:
	host/build/lnteehost ./enclave/build/lntee.signed 10024

run27:
	host/build/lnteehost ./enclave/build/lntee.signed 10025

run28:
	host/build/lnteehost ./enclave/build/lntee.signed 10026

run29:
	host/build/lnteehost ./enclave/build/lntee.signed 10027

run30:
	host/build/lnteehost ./enclave/build/lntee.signed 10028

simulate:
	host/lnteehost ./enclave/lntee.signed --simulate