// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payload.proto

#ifndef PROTOBUF_INCLUDED_payload_2eproto
#define PROTOBUF_INCLUDED_payload_2eproto

#include <limits>
#include <string>

namespace payload
{

enum MESSAGE_TYPE
{
    Internet_connection = 0,
    Internet_connection_res,
    Internet_connection_final,
    Initialize_from_blockchain,
    Register_to_blockchain,
    Update_initial_state,
    Claim_recv_asset,
    Verify_initial_state,
    Verify_initial_state_res,
    Send_host_to_enc,
    Send_transaction,
    Contract_transaction,
    Direct_tranaction,
    End_contract_instance,
    Internet_test,
    Internet_test_res
};
}
#endif // PROTOBUF_INCLUDED_payload_2eproto
